package com.order.models;

public enum ProductType {
    MAINTENANCE_APPLICATION,
    MAINTENANCE_CONTRACT,
    PHYSICAL_PRODUCT,
    BOOK,
    VIDEO,
    MEMBERSHIP_ACTIVATION,
    MEMBERSHIP_UPGRADE
}
